version: '3'

services:

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testDB



  chat-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: chandra/java-rest-ws
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always
